name: Issue workflow

on:
  issues:
    types: [opened, closed, edited, reopened]
  pull_request:
    types: [opened, closed]
  workflow_dispatch: 
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run tests
        run: |
            ls
            python pytest.py
          # Run your test cases here
          # Exit with non-zero status if tests fail
      
      - name: Comment on issue
        if: ${{ github.event_name == 'issues' }}
        run: |
          # Add a comment to the issue with test results
      
#       - name: Automatically close issues that don't follow the issue template
#         uses: lucasbento/auto-close-issues@v1.0.2
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           issue-close-message: "@${issue.user.login}: hello! :wave:\n\nThis issue is being automatically closed because it does not follow the issue template." # optional property
#           closed-issues-label: "🙁 Not following issue template" # optional property
     
      - name: Update issue status
        uses: peter-evans/update-issue@v1
        with:
         repo-token: ${{ secrets.GIT_SECRET }}
         issue-number: 1
         state: closed

      
#       - name: to Close issue
#         #if: ${{ github.event_name == 'issues' && github.event.action == 'closed' && success() }}
#         run: |
#             github.issues.update({
#               owner: 'owner-name',
#               repo: 'repo-name',
#               issue_number: 1,
#               state: 'closed'
#                 })
#             github-token: ${{ secrets.GIT_SECRET }}
#           # Close the issue
        #if: github.event.label.name == 'close'
      
#       - name: Close pull request
#         if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && success() }}
#         run: |
#           # Close the pull request
