name: Issue workflow

on:
  issues:
    types: [opened, closed, edited, reopened]
  pull_request:
    types: [opened, closed]
  workflow_dispatch: 
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run tests
        run: |
            ls
            python pytest.py
          # Run your test cases here
          # Exit with non-zero status if tests fail
          
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Usage
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: |
          echo $TIME
      
#       - name: Comment on issue
#         if: ${{ github.event_name == 'issues' }}
#         run: |
#           # Add a comment to the issue with test results
#               github.issues.update({
#               issue_number: ${{ github.event.issue.number }},
#               state: 'closed'
#                })
#       - name: updating in Release
#         uses: ncipollo/release-action@v1
#         with: 
#           tag: ${{steps.date.outputs.date}}
#           artifacts: "./report/report.html"
#           replaceartifacts: true
      - name: "Build & test"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GIT_SECRET }}"
          automatic_release_tag: "${{TIME}}"
          prerelease: true
          title: "Development Build"
          files: |
            pytest.py
