name: Issue workflow

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, closed]
  workflow_dispatch: 
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          xvfb \
          libgtk-3-0 \
          libnotify-dev \
          libgconf-2-4 \
          libnss3 \
          libxss1 \
          libasound2

      - name: Install pytest-playwright
        run: |
          pip install pytest-playwright   
     
      - name: Run tests
        run: |
            ls
            python ./dummy/main.py
          # Run your test cases here
          # Exit with non-zero status if tests fail
          
#       - name: Get Time
#         id: time
#         uses: nanzm/get-time-action@v1.1
#         with:
#           timeZone: 8
#           format: 'YYYY-MM-DD-HH-mm-ss'
          
      - name: Create TAG
        run: |
            TAG_NAME=$(date +'%Y%m%d-%H%M%S')
        id: clean_time
        env:
          CLEAN_TIMESTAMP: ${{ steps.clean_time.outputs.TAG_NAME }}
      
#       - name: "Build & test"
#         run: |
#           echo "done!"
          
#       - name: Create release
#         uses: marvinpinto/action-automatic-releases@latest
#         with:
        
#           repo_token: "${{ secrets.GIT_SECRET }}"
#           automatic_release_tag: "${{ env.CLEAN_TIMESTAMP }}"
#           prerelease: true
#           title: "Development Build"
#           files: |
#             ./dummy/report.html
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.CLEAN_TIMESTAMP }}
          artifacts: "./dummy/report/report.html"
          replacesArtifacts: false
