name: Issue workflow

on:
  issues:
    types: [opened, closed, edited, reopened]
  pull_request:
    types: [opened, closed]
  workflow_dispatch: 
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run tests
        run: |
            ls
            python pytest.py
          # Run your test cases here
          # Exit with non-zero status if tests fail
          
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Usage
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: |
          echo $TIME
      
      - name: "Build & test"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GIT_SECRET }}"
          automatic_release_tag: "${{ env.TIME }}"
          prerelease: true
          title: "Development Build"
          files: |
            pytest.py
