name: Issue workflow

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, closed]
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          xvfb \
          libgtk-3-0 \
          libnotify-dev \
          libgconf-2-4 \
          libnss3 \
          libxss1 \
          libasound2

      - name: Install pytest-playwright
        run: |
          pip install pytest-playwright

      - name: Run tests
        run: |
          pytest ./dummy/main.py

      - name: Create TAG
        run: |
          TAG_NAME=$(date +'%Y%m%d-%H%M%S')
          echo "::set-output name=tag_name::$TAG_NAME"
        id: tag

      - name: Create release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          release_name: Release ${{ steps.tag.outputs.tag_name }}
          body: Automated release created by GitHub Actions
          draft: false
          prerelease: false

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: ./dummy/report.html
