name: Issue workflow

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, closed]
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          xvfb \
          libgtk-3-0 \
          libnotify-dev \
          libgconf-2-4 \
          libnss3 \
          libxss1 \
          libasound2

      - name: Install pytest-playwright
        run: |
          pip install pytest-playwright

      - name: Run tests
        run: |
          pytest ./dummy/main.py

      - name: Create tag
        id: tag
        run: echo ::set-output name=tag::$(date +'%Y%m%d-%H%M%S')
     #     echo "name=tag_name::$TAG_NAME" >> $GITHUB_ENV

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_SECRET }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Release ${{ steps.tag.outputs.tag }}
          body: |
            Release ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: true
          files: |
             ./dummy/report.html
#       - name: Create release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GIT_SECRET }}
#         with:
#           tag_name: ${{ steps.tag.outputs.tag }}
#           release_name: Release ${{ steps.tag.outputs.tag }}
#           body: |
#             Release ${{ steps.tag.outputs.tag }}
#           draft: false
#           prerelease: true
#           files: |
#              ./dummy/report.html

#       - name: Upload report
#         uses: actions/upload-artifact@v2
#         with:
#           name: Test report
#           path: ./dummy/report.html
